# Generated by Django 4.2 on 2023-05-02 04:02

import apps.home.models
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.home.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_chain_of_custody',
            field=models.ManyToManyField(related_name='evidence_chain_of_custody', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.UUIDField(default=uuid.UUID('ef0a8c93-0a18-4da9-9798-ca5a74695b8b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_id',
            field=models.UUIDField(default=uuid.UUID('8a9cf65d-c53a-4bb2-b838-5f00d52524f7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_id',
            field=models.UUIDField(default=uuid.UUID('5e9fd04e-f963-47b7-bb54-65c3a96bc7ea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
