# Generated by Django 4.2 on 2023-05-02 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_status',
            new_name='case_is_open',
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.UUIDField(default=uuid.UUID('46cb86fd-9a33-40c2-adc6-d9925845dc23'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_id',
            field=models.UUIDField(default=uuid.UUID('0843fe00-ed8f-4070-830a-552c9029769f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_id',
            field=models.UUIDField(default=uuid.UUID('0652df39-8a91-4427-9036-1405e5e849d0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
