# Generated by Django 4.2 on 2023-05-02 15:00

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_case_status_case_case_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_member',
            field=models.ManyToManyField(related_name='case_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.UUIDField(default=uuid.UUID('52638a1a-bc82-49d4-835b-54ac8816ae1b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_id',
            field=models.UUIDField(default=uuid.UUID('c9a8a82e-3948-4bb5-9dfc-0ee7e905d5be'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_id',
            field=models.UUIDField(default=uuid.UUID('e38a6097-a7f9-42dc-8825-1973b774caf5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
