# Generated by Django 4.2 on 2023-05-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_evidence_evidence_acquired_by_alter_case_case_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence_acquired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_file_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
