# Generated by Django 4.2 on 2023-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_evidence_evidence_acquired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence_status',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
