# Generated by Django 4.2 on 2023-05-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_evidence_evidence_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='evidence_chain_of_custody',
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_chain_of_custody',
            field=models.JSONField(default=list),
        ),
    ]
