# Generated by Django 5.0.1 on 2024-02-29 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_evidence_evidence_chain_of_custody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('acquisition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquisition_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('acquisition_partition_id', models.CharField(max_length=100)),
                ('acquisition_transferred_bytes', models.BigIntegerField(default=0)),
                ('acquisition_total_bytes', models.BigIntegerField(default=0)),
                ('acquisition_unique_link', models.CharField(max_length=255, unique=True)),
                ('acquisition_type', models.CharField(max_length=50)),
                ('acquisition_date', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='home.evidence')),
            ],
        ),
    ]
