# Generated by Django 5.0.3 on 2024-03-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_acquisition_acquisition_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_resume_from_byte',
            new_name='acquisition_size',
        ),
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_total_bytes',
            new_name='acquisition_total_transferred_bytes',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_transferred_bytes',
        ),
    ]
