# Generated by Django 5.0.3 on 2024-03-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_acquisition_resume_from_byte_acquisition_acquisition_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_partition_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_total_transferred_bytes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='home.evidence'),
        ),
    ]
