# Generated by Django 5.0.3 on 2024-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_acquisition_acquisition_partition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='acquisition_device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
