# Generated by Django 5.0.3 on 2024-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_acquisition_acquisition_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='acquisition_client_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='acquisition_custom_port',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='acquisition_full_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
