# Generated by Django 5.0.3 on 2024-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_acquisition_acquisition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_size_template',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
