# Generated by Django 5.0.3 on 2024-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_acquisition_acquisition_is_verify_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='acquisition_hash_verify',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
