# Generated by Django 5.0.3 on 2024-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_acquisition_acquisition_hash_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
