# Generated by Django 5.1.1 on 2024-09-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_acquisition_acquisition_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullFileSystemAcquisition',
            fields=[
                ('acquisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='full_file_system', serialize=False, to='home.acquisition')),
                ('file_system_type', models.CharField(blank=True, max_length=100, null=True)),
                ('root_directory', models.CharField(blank=True, max_length=255, null=True)),
                ('total_files', models.IntegerField(blank=True, null=True)),
                ('total_size', models.BigIntegerField(blank=True, null=True)),
                ('hash_result', models.CharField(blank=True, max_length=64, null=True)),
                ('excluded_files', models.JSONField(blank=True, null=True)),
                ('encryption_status', models.BooleanField(default=False)),
                ('decryption_method', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogicalAcquisition',
            fields=[
                ('acquisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='logical', serialize=False, to='home.acquisition')),
                ('data_types_acquired', models.JSONField(blank=True, null=True)),
                ('selected_applications', models.JSONField(blank=True, null=True)),
                ('selected_files', models.JSONField(blank=True, null=True)),
                ('user_accounts', models.JSONField(blank=True, null=True)),
                ('total_records', models.IntegerField(blank=True, null=True)),
                ('hash_result', models.CharField(blank=True, max_length=64, null=True)),
                ('acquisition_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAcquisition',
            fields=[
                ('acquisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='physical', serialize=False, to='home.acquisition')),
                ('partition_id', models.CharField(blank=True, max_length=100, null=True)),
                ('partition_size', models.BigIntegerField(blank=True, default=0, null=True)),
                ('hash_before_acquisition', models.CharField(blank=True, max_length=64, null=True)),
                ('hash_after_acquisition', models.CharField(blank=True, max_length=64, null=True)),
                ('is_verify_first', models.BooleanField(blank=True, null=True)),
                ('total_transferred_bytes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('acquisition_method', models.CharField(blank=True, max_length=50, null=True)),
                ('source_device', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('encryption_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_device_id',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_file_name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_full_path',
            new_name='full_path',
        ),
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_last_active',
            new_name='last_active',
        ),
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='acquisition',
            old_name='acquisition_unique_link',
            new_name='unique_link',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_client_ip',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_custom_port',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_hash',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_hash_verify',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_is_verify_first',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_method',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_partition_id',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_size_template',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_status',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='acquisition_total_transferred_bytes',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='connection_type',
            field=models.CharField(choices=[('USB', 'USB'), ('WiFi', 'WiFi')], default='USB', max_length=10),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('full_file_system', 'Full File System'), ('logical', 'Logical'), ('physical', 'Physical')], max_length=20, null=True),
        ),
    ]
