# Generated by Django 5.1.1 on 2024-09-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_fullfilesystemacquisition_logicalacquisition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalacquisition',
            name='hash_after_acquisition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalacquisition',
            name='hash_before_acquisition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
