# Generated by Django 5.1.1 on 2024-10-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_physicalacquisition_hash_after_acquisition_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
