# Generated by Django 5.1.1 on 2024-10-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
    ]
