# Generated by Django 5.1.1 on 2024-10-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_acquisition_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='size',
        ),
    ]
