# Generated by Django 5.1.2 on 2024-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_case_notes_case_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
