# Generated by Django 5.1.2 on 2024-10-31 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_evidence_evidence_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectiveFullFileSystemAcquisition',
            fields=[
                ('acquisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='selective_full_file_system', serialize=False, to='home.acquisition')),
                ('selected_applications', models.JSONField(blank=True, null=True)),
                ('total_records', models.IntegerField(blank=True, null=True)),
                ('hash_result', models.CharField(blank=True, max_length=64, null=True)),
                ('acquisition_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LogicalAcquisition',
        ),
    ]
