# Generated by Django 5.1.2 on 2024-10-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_selectivefullfilesystemacquisition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('full_file_system', 'Full File System'), ('selective_full_file_system', 'Full File System (Selective)'), ('logical', 'Logical'), ('physical', 'Physical')], max_length=30, null=True),
        ),
    ]
