# Generated by Django 5.1.2 on 2024-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_acquisition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
