# Generated by Django 5.1.2 on 2024-12-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_acquisition_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidence',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
