# Generated by Django 5.1.2 on 2024-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_case_is_deleted_evidence_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalacquisition',
            name='format_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
