# Generated by Django 5.1.2 on 2024-12-11 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_physicalacquisition_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
